# -*- coding: utf-8 -*-
"""analise_exploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kcv9QnDwa1bimw-etnBPn3zBIVcEjuK4
"""

import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn")

from google.colab import files
arq = files.upload()

df = pd.read_excel("AdventureWorks.xlsx")

df.head()

df.shape

df.dtypes

#Receita Total
df["Valor Venda"].sum()

#Custo Total
df["Custo"] = df["Custo Unitário"].mul(df["Quantidade"]) #Coluna de Custos

#Custo Total
round(df["Custo"].sum(), 2)

df["Lucro"] = df["Valor Venda"] - df["Custo"]

df.head(1)

#Lucro Total
round(df["Lucro"].sum(), 2)

#Coluna total de dias para enviar o produto
df["Tempo de Envio"] = df["Data Envio"] - df["Data Venda"]

df.head(1)

#Extraindo os dias
df["Tempo de Envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days

df.head(1)

df["Tempo de Envio"].dtype

#Média do tempo de envio por Marca
df.groupby("Marca")["Tempo de Envio"].mean()

#Verificar dados faltantes
df.isnull().sum()

#Agrupar por ano e marca
df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum()

pd.options.display.float_format = '{:20,.2f}'.format

#Resentando o index
lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum().reset_index()
lucro_ano

#Total Produtos Vendidos
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False)

#Gráfico Total Produtos Vendidos
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title = "Total Produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produto");

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum().plot.bar(title = "Lucro x Ano")
plt.xlabel("Ano")
plt.ylabel("Receita");

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum()

#Selecionando Vendas 2009
df_2009 = df[df["Data Venda"].dt.year == 2009]

df_2009.head()

df_2009.groupby(df_2009["Data Venda"].dt.month)["Lucro"].sum().plot(title = "Lucro x Mês")
plt.xlabel("Mês")
plt.ylabel("Lucro");

df_2009.groupby("Marca")["Lucro"].sum().plot.bar(title = "Lucro x Marca")
plt.xlabel("Marca")
plt.ylabel("Lucro")
plt.xticks(rotation = 'horizontal');

df_2009.groupby("Classe")["Lucro"].sum().plot.bar(title = "Lucro x Classe")
plt.xlabel("Classe")
plt.ylabel("Lucro")
plt.xticks(rotation = 'horizontal');

df["Tempo de Envio"].describe()

#Gráfico de Boxplot
plt.boxplot(df["Tempo de Envio"]);

#Histograma
plt.hist(df["Tempo de Envio"]);

#Tempo Mínimo Envio
df["Tempo de Envio"].min()

#Tempo Máximo Envio
df["Tempo de Envio"].max()

#Identificando Outlier
df[df["Tempo de Envio"] == 20]

df.to_csv("df_vendas_novo.csv", index=False)